# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9f9457713ddcef5f0613e2d2b6e7fa9429a096dbf7220229cdee6cd759ae8a5f5762353d3a66fc01ccc0dc0762727e2f48cc7b58025a5f191377c459b09449

test:
  secret_key_base: fff30154acf32c3397c230e71ecca4dae9dac774340904bca23ea696b9a50eb46ca4f464649d175f80d47cc0efc51ae4271472fad15f896998efc0d7d16ecac3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
